[BOJ] 1446 소가 길을 건너간 이유 1
hufslion10th/HUFSALGO pull request #7
Opened 2022-07-12 15:59 UTC by 4923

## 로직 개요
Python / BOJ / Implication, Math

- 구해야 하는 것: 문제 마지막줄에 요약해 준다. '같은 번호의 소가 위치를 바꾼 것이 몇 번인가?'
- 문제의 solution key를 좌표값으로 보았음. (왼쪽을 0, 오른쪽을 1)
- 길을 건넜을때의 합이 0+1으로 1인데, 이를 계속해서 누적하면 값이 발산하므로 **합이 0이 되도록** if문으로 값을 조정함.

- for문으로 배열을 전부 탐색하면 답은 금방 나오겠으나 쉽게 풀 수 있는 방법이 있다고 생각했음.
- 최대값이 100 (관찰횟수 N) 이고 배열을 생성했을때 요소값이 10 (소의 수) 이므로 기하급수적으로 수가 커지지는 않겠지만 O(N) 정도로 풀고자 함.

### 결과: 오답
- 길의 왼쪽과 오른쪽의 차이는 1이라는 점에 착안해서 풀었으나 [RundimeError: Index] 제출시 발생
- [ ] 엣지케이스를 생성하기엔 매 값을 넣어줘야하니 코드 다시한번 보며 인덱스 밖으로 나가는게 없는지 확인
- [ ] 너무 오랜만에 알고리즘을 풀고 있으니 인덱스 에러가 발생하는 또 다른상황을 확인해 볼것

2022-07-12 16:00 UTC, 4923 commented on BOJ/14467/4923.py
> +    log[number] += position
- [ ] Dictionary 를 쓰려고 했으나 아예 값이 초기화되지 않고서 `+=` 연산자를 사용할 수 없었음 -> 어차피 소의 수 10마리이므로 수동으로 0을 할당해볼 것

2022-07-12 16:25 UTC, Parkjju requested changes

2022-07-12 16:25 UTC, Parkjju commented on BOJ/14467/4923.py
> +    log[number] += position
https://github.com/Parkjju/HUFSALGO/blob/896c0365b4f86c56a9c3643c5d03796a799c9169/BOJ/14467/Parkjju.js#L25-L28

자바스크립트의 경우 Object 타입이 파이썬 딕셔너리와 유사한데
객체에 없는 키값에 접근할 경우 자동으로 `undefined`를 반환하게 됩니다.

그래서 저는 소 번호에 따라서 위치 초기화 시킬때 
`if 객체[소 번호] === undefined`라는 로직을 사용하긴 했는데

어차피 소 번호를 키 값으로 갖는 Value값이 
계속 증가하는 카운트 형태가 아니라

True / false 또는 0 / 1 또는 왼쪽 / 오른쪽의 형태라

소 번호를 0~9까지의 인덱스로 잡고
소 번호 인덱스에 따른 배열 값을 0 또는 1로 초기화하면 될 것 같습니닷

2022-07-12 16:25 UTC, Parkjju commented on BOJ/14467/4923.py
> +        result[number] += 1
반례 제시)
3
1 1
1 1
1 0

1번 소가 1번 위치에서 두번 발견되고
마지막에 0번에서 발견되었다고 가정하면

for문 끝까지 순회한 결과 `position`값이 최종 1로 남게 되네요
제 생각에 `log[number] += position`이 아니라 
flag형태로 `log[number] = !position` 이런 형태로 가져가야 
소의 위치를 제대로 표현할 수 있지 않을까 싶습니다 👍

2022-07-15 03:46 UTC, closed without merging

2022-07-19 12:57 UTC, 4923 commented on BOJ/14467/4923.py
> +    log[number] += position
4f388bb2d8fa618c9abbed410c1e3a4eb4c546dd 해당 커밋에서 해결
- 로직이 주인 문제이므로 구현 방법은 사실 큰 관계가 없어보임

2022-07-19 13:00 UTC, 4923 commented on BOJ/14467/4923.py
> +        result[number] += 1
반례 감사합니다. 해당 부분은 해결했습니다! (26018cc4c000e17b1edecd5d25a4f51b1ac795ef) 👍

2022-07-19 13:06 UTC, 4923 commented on BOJ/14467/4923.py
> +        result[number] += 1
어?! 커밋메시지에 '입력이 이렇게 주어지지는 않을것 같다'고 적었는데 예시입력에 3 0 ... 3 0이 있었네요 
이걸 놓쳤네... 경준님 감사합니다 💯

2022-07-19 13:08 UTC, Parkjju commented on BOJ/14467/4923.py
> +        result[number] += 1
ㅋㅋㅋㅋㅋㅋㅋㅋ저도 그거 놓쳤었어요.....뒷통수

2022-07-19 13:37 UTC, 4923 commented on BOJ/14467/4923.py
> +    log[number] += position
열심히 쓰고 있었는데... 커맨드 화살표는 뒤로가기 단축키였네요

최대한 혼자 풀어보고 싶어서 풀다풀다 잡다한거 다 지우고 결국 `!=` 연산자 하나로만 풀었는데 해설해주신대로 None으로 list를 채우면 `+=` 연산자가 안되고... 그래서 입력값으로 아예 들어올 수 없는 값을 관찰한 값으로 넣었더니 맞았네요.

```py
# 여기서 movement_log 를 [None for ~~~] 로 하지 않고 -1로 하고
movement_log = [-1 for _ in range(11)]  # 소의 번호와 위치를 연산한 결과

# movement_log[cow_number] == -1 일 때는 소를 처음으로 관찰한 때이므로 조건 중 하나로 추가하는 형식으로요
 if movement_log[cow_number] != -1 and movement_log[cow_number] != current_position:
...
```

하여간 처음 코드에서  대충 반절로 코드가 줄어서 허망하지만 덕분에 풀었습니다... 감사합니다
게다가 자스 특징도 덤으로 알아갑니다 최고의 자스마스터 👍 💯 🥇

2022-07-19 13:48 UTC, 4923 commented
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/60145951/179764538-77a1a2cb-96af-4a2f-a85a-8b0b6eb4089d.png">

맞았다고 확신하고 제출했을 때 틀리면 채점 시스템을 믿을 수 없어서 괜히 자잘한거 하나 고치고 다시 채점해보는 습관이 있습니다
그리고 중간 출력문을 깜빡하는 버릇도...

### 오답노트
1. 런타임 에러: 4f388bb2d8fa618c9abbed410c1e3a4eb4c546dd / 리스트는 0부터 시작하는 인덱스로 접근하고, 소의 번호는 1부터 시작하니 소의 번호를 인덱스로 삼으려면 리스트의 전체 값이 11개여야 했습니다.
2. 경준님이 주신 반례 해결했지만 여전히 오답: 26018cc4c000e17b1edecd5d25a4f51b1ac795ef / 같은 자리에 있을 경우를 생각하지 않아서 *소가 이동했을때 위치값의 합은 0이다* 라고 생각한건데 지금 보니 예제에 3 0 ... 3 0이 있었네요. 그래서 위치의 합을 이용하는 방법은 접었습니다.
3. 그렇다면 2 에서 조건으로 넣었던 이전 위치와 현재 위치가 같지 않을때 `!=` 를 찾으면 되는데 소의 위치를 기록하는 list의 초기값을 None으로 하면 PR의 첫 description 에 적은 것 처럼 덧셈이 안되고 0으로 하면 0 또한 위치로 잡혀서 최종 이동 횟수가 두배가 됩니다. (처음부터 이동 위치가 1로 주어진 경우 초기 위치가 0이므로 첫 관측부터 이동횟수가 1이 되는 경우) 따라서 입력값으로 주어지지 않을 수인 -1을 주고, -1이 아닌 경우를 조건으로 추가했습니다.

3번을 말로 하니까 복잡한데 대략 코드는 이러합니다.

```py
# [오답노트 1] 일단 for _ 으로 둔 이상 range 가 1, 11 이든 0, 10 이든 상관이 없다. 10자리만 나오고 그 index는 전부 같기 때문. 차라리 0, 11로 하는게 낫다.
movement_log = [-1 for _ in range(11)]  # 소의 번호와 위치를 연산한 결과
movement_result = [0 for _ in range(11)]    # 길을 건넌 횟수를 기록하는 리스트

# -- 2. 계산 -- #
# 관찰 결과를 입력받으며 위치를 조정
for i in range(N):
    cow_number, current_position = map(int, sys.stdin.readline().strip().split())
    
    # [오답노트 3] movement_log[cow_number] == -1 일 때는 소를 처음으로 관찰한 때다.
    if movement_log[cow_number] != -1 and movement_log[cow_number] != current_position:  # [오답노트 2]
        movement_result[cow_number] += 1    
    movement_log[cow_number] = current_position # 현재 위치로 초기화
```

reopen 하고 머지하려고 했는데 이미 머지된게 있어서 reopen이 안된다고 하네요. 다른 커밋이 쌓였나봅니다.
머지용 PR 하나만 열었다가 닫겠습니다.

2022-07-19 15:53 UTC, Parkjju commented
ㅋㅋㅋㅋㅋ 고생하셨습니다 💯